language: node_js
node_js:
- '8'
- 'node'
before_deploy:
- npm-prepublish --verbose --lax
deploy:
  provider: npm
  email: denisgranha@gmail.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    node: '8'
    repo: gnosis/olympia-token
