language: node_js
node_js:
- '8'
- 'node'
deploy:
  provider: npm
  email: denisgranha@gmail.com
  api_key: $NPM_TOKEN
  on:
    all_branches: true
    tags: true
    node: '8'
    repo: gnosis/pm-apollo-contracts
